name: Build & Test

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install deps, node ci
        run: npm ci
      - name: Test
        run: npm run test